### PR TITLE
Owner acct

### PR DESCRIPTION
**Pull request by nyashafrank**
Set up basic account page. User visits account page, and services that they own are listed. Each service card has an edit and delete button. Buttons are not functional though.

### CODE REVIEW

**Comment by nyashafrank** [comment]
wait don't pull yet

**Comment by abeSanchez** [comment]
pull out?

**Comment by steevejoseph** [comment]
> pull out?

never that

**Comment by abeSanchez** [comment]
oh shit plan b

**Comment by steevejoseph** [comment]
💯

**Pull request merged**
