### PR TITLE
option things

### PR DESCRIPTION
**Pull request by abeSanchez**
options only show if service has options
service price is the starter tier price
didnt really go all in on the form errors but this will do 
sorry this file has gotten messy

### CODE REVIEW

**Comment by abeSanchez** [comment]
my 'Options test' service  under Graphics & Design demos it nicely

**Comment by nyashafrank** [comment]
oh me oh my what an upgrade

I like the alliteration with the three S's, has a nice ring to it. Thoughts on modifying Super to Premium? Also, not sure if this affects anything, but in service_view in renderCarousel, is it okay that it says class instead of className?

**Comment by abeSanchez** [comment]
alliteration for a more lit demo

**Comment by abeSanchez** [comment]
true true will change to className in my next PR

**Pull request merged**
