### PR TITLE
Service View Renovation + Goodies

### PR DESCRIPTION
**Pull request by abeSanchez**
ServiceView layout modified, but still needs some filling in. Things are in a decent spot though.
- Service descriptions are now converted from markdown to jsx.
- User and Options now appear as placeholders
- Change of color to rating stars for now
- Photo stuff still needs to be done
- Loader added as well

### CODE REVIEW

**Comment by abeSanchez** [comment]
/services/5bf708f9ac53ba0016164a68 is a good service to look at for a markdown example

**Comment by abeSanchez** [comment]
oh yeah create review only shows up if your logged in and its not your service

**Comment by nyashafrank** [comment]
jaw dropped... you done did it again  👏  🔥👏😮 🔥 🙌 

P.S. create service will need to be updated for the options thing, and it'll be optional to have?

**Comment by abeSanchez** [comment]
yes i know create and edit service needs some work for both options and the new Markdown thing

**Pull request merged**
