### PR TITLE
category descrip added.

### PR DESCRIPTION
**Pull request by alittlebirdie00**

### CODE REVIEW

**Comment by abeSanchez** [comment]
Just a couple punctuation issues

**Comment by alittlebirdie00** [comment]
> Just a couple punctuation issues

Thanks. Which lines?

**Comment by abeSanchez** [comment]
my bad.  "Your beautiful. Make yourself look like a snack with Beauty."

**Comment by abeSanchez** [comment]
you're*

**Comment by abeSanchez** [comment]
actually thats the only one

**Comment by alittlebirdie00** [comment]
> you're*

;) Thanks for the compliment Abe

**Comment by alittlebirdie00** [comment]
Changing it now

**Comment by alittlebirdie00** [comment]
done

**Pull request merged**
